{% set version = "5.3.0" %}

package:
  name: gidgethub
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gidgethub/gidgethub-{{ version }}.tar.gz
  sha256: 9ece7d37fbceb819b80560e7ed58f936e48a65d37ec5f56db79145156b426a25

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m flit install --deps=none

requirements:
  host:
    - python >=3.6
    - flit
  run:
    - cryptography >=2.9
    - pyjwt >=1.7.1
    - python >=3.6
    - uritemplate >=3.0.1


test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - gidgethub

about:
  home: https://gidgethub.readthedocs.io/en/latest/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: An async GitHub API library for Python

  doc_url: https://gidgethub.readthedocs.io/en/latest/
  dev_url: https://github.com/brettcannon/gidgethub

extra:
  recipe-maintainers:
    - asmeurer
    - ocefpaf
