travis:
  secure:
    BINSTAR_TOKEN: oBkinrIfGuGhl8JCWuMbDDXKKJoVzC7ydRmJ8O9gqbpYSOvice0YkU8vhH6lXR9ZvkrDsUimwUhFz/RfdogvptDlYHgVIDhsf6IYxHHbqMHF3Jy7oJ4b+KqwkLvivxiDMcVgCx1kvMkp4qabOfje5Kh+OC0bM6ne/0A/qnjwtW9KRFwdVLjSJFudHZD1LkXGN3OKQhFoVATknFIrUKZZ1BPMjCEDKYC10O2NlUGR/HGnaSXvTt400V/p3TBhkUQL4OQgFozr/ordd4OepBDFKmeTDbqQ3Enpw3o/KTPHUr0Zbr26TNNdDCSed5q2OeKbz7t6gLxvI5P6PsaT9lc118TLzB72d6NIRAhSQEpIsKE72z9ytEPTKFy4LGvKwU0VTk2+2kvkEdnVLLVQ6sQmMqZi8OWelAj/Tb/3oQMTnbV2InnXKIi409eYLxf6W30aYmUgFfE1jR39TB2+GbCyKY7af/Qag2ro5QeD3AIhhACpaRxjgJ78Xsnf71NztNA9QMKXRK87vEv0ihoCjKaO6sPAqzEvUQ9FaF8OXUSYS2O5KOZ9J4UmVTGnX3psm5uCznwKqEoqp+/NkAfe2/TGBduoV+HRBq79t53R3DDYSBk0pbJ42mrLCQwIExq/lGF2mne75A6fMfLwZWp9WBlgTbWEXwKyVsjjyH2QsjCc/AA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
